// <auto-generated />
namespace ShopAppK300.Entities.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class ProPicture : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ProPicture));
        
        string IMigrationMetadata.Id
        {
            get { return "202006121835284_ProPicture"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
